INSERT INTO jobs(title,company_id,city)
VALUES
('(Junior / Senior) Pre - Sales Manager',141,'Berlin'),
('(Junior) Data Analyst',20,'Düsseldorf'),
('(Junior) HR Business Partner',67,'Berlin'),
('(Junior) Influencer Manager',140,'Berlin'),
('(Junior) Inside Sales Manager / Vertriebsinnendienst',141,'Berlin'),
('(Junior) Java Software Engineer [#781]',52,'Munich'),
('(Junior) Marketing Manager - Website',104,'Munich'),
('(Mid/Senior) Full-Stack Engineer  (Berlin, full-time)',74,'Berlin'),
('(Operations) Business Intelligence Manager',67,'Berlin'),
('(PHP) Web Developer',113,'Berlin'),
('(Senior) Configuration Management Engineer',84,'Munich'),
('(Senior) Content Marketing Manager',104,'Munich'),
('(Senior) Controller)',67,'Berlin'),
('(Senior) Data Engineer / Business Intelligence Platform / Berlin',95,'Berlin'),
('(Senior) Finance Manager - Controlling and FP&A',58,'Berlin'),
('(Senior) Financial Software Engineer',34,'Berlin'),
('(Senior) Frontend Developer',3,'Berlin'),
('(Senior) Group Accountant',143,'Berlin'),
('(Senior) International Communications Manager',113,'Berlin'),
('(Senior) International Communications Manager',113,'Berlin'),
('(Senior) Learning & Development Specialist',104,'Munich'),
('(Senior) Perl Developer',113,'Berlin'),
('(Senior) Product Manager',71,'Berlin'),
('(Senior) Product Manager- New Markets',68,'Berlin'),
('(Senior) QA/Test Engineer',35,'Munich'),
('(Senior) Qualitätsmanager Customer Service',113,'Berlin'),
('(Senior) Ruby Developer',3,'Berlin'),
('(Senior) Sales Manager Berlin',46,'Berlin'),
('(Senior) Security Engineer',113,'Berlin'),
('(Senior) Security Engineer',104,'Munich'),
('(Senior) SharePoint and Office 365 Solution Consultant',22,'Munich'),
('(Senior) Software Engineer',58,'Berlin'),
('(Senior) Software Engineer (Back-End)',113,'Berlin'),
('(Senior) Software Engineer (Front-End)',113,'Berlin'),
('(Senior) Talent Attraction Partner',70,'Berlin'),
('(Senior) Talent Attraction Partner - Tech',70,'Berlin'),
('(Senior) Test Automation Engineer',113,'Berlin'),
('(Senior) Trainer Personio Academy',104,'Munich'),
('12 Months Fixed Term Associate Advocacy Officer, Justice Initiative',96,'Berlin'),
('Account Development Representative - DACH',144,'Berlin'),
('Account Executive',92,'Munich'),
('Account Executive',112,'Munich'),
('Account Executive',27,'Berlin'),
('Account Executive',13,'Berlin'),
('Account Executive',57,'Hamburg'),
('Account Executive - Cyber Security - Frankfurt',44,'Frankfurt'),
('Account Executive - Cyber Security - Munich',44,'Munich'),
('Account Executive - DACH',69,'Hamburg'),
('Account Executive - Germany',80,'Munich'),
('Account Executive 🇩🇪(Berlin)',133,'Berlin'),
('Account Executive Benelux',104,'Munich'),
('Account Executive DACH',104,'Munich'),
('Account Executive EMEA (Berlin)',24,'Berlin'),
('Account Executive Germany - Berlin',24,'Berlin'),
('Account Executive Nordics',104,'Munich'),
('Account Executive, Large Enterprise (DACH)',124,'Munich'),
('Account Executives - Germany',49,'Berlin'),
('Account Manager',4,'Berlin'),
('Account Manager',60,'Berlin'),
('Account Manager',150,'Munich'),
('Account Manager',25,'Berlin'),
('Account Manager',112,'Munich'),
('Account Manager',13,'Berlin'),
('Account Manager',4,'Munich'),
('Account Manager - DACH',36,'Berlin'),
('Account Manager [DACH]',2,'Berlin'),
('Account Manager [DACH]',2,'Munich'),
('Account Manager Inside Sales - UK',110,'Munich'),
('Account Manager Payroll',104,'Munich'),
('Account Manager- HelloFreshGO',67,'Berlin'),
('Accountant',16,'Berlin'),
('Accounting Manager',131,'Berlin'),
('Accounting Manager',143,'Berlin'),
('Accounting Manager',95,'Berlin'),
('Agile Coach',67,'Berlin'),
('Agile Coach',122,'Berlin'),
('Agile Operations and Tools Expert',131,'Berlin'),
('Android Engineer',131,'Berlin'),
('Android Engineer (Java/Kotlin)',141,'Berlin'),
('Anlagenmeachniker / Monteur- Region Elmshorn',141,'Hamburg'),
('Anlagenmechaniker / Meister / Techniker im Innendienst | Kundendienst',141,'Berlin'),
('Anlagenmechaniker / Meister / Techniker im Innendienst | Kundendienst',141,'Berlin'),
('Anlagenmechaniker / Monteur - Region Frankfurt am Main',141,'Frankfurt'),
('Anlagenmechaniker / Monteur - Region Hamburg',141,'Hamburg'),
('Anlagenmechaniker / Monteur - Region Karlsruhe',141,'Karlsruhe'),
('Anlagenmechaniker / Monteur - Region Nürnberg',141,'Berlin'),
('Anlagenmechaniker / Monteur- Region München',141,'Munich'),
('API Integrations Lead',47,'Berlin'),
('Application Security Engineer',39,'Berlin'),
('Application Support Engineer',121,'London'),
('Applications Engineer',145,'Munich'),
('Art Director',125,'Helsinki'),
('Assembly Worker',110,'Munich'),
('Assistenz/ Sachbearbeitung Buchhaltung',91,'Aachen'),
('Associate Corporate Finance',82,'Hamburg'),
('Associate Director International Payments',67,'Berlin'),
('Aushilfe/Werkstudent Logistik',91,'Aachen'),
('Außendienstmitarbeiter / Vertriebsmitarbeiter - Region Mönchengladbach',141,'Berlin'),
('Automation Engineer  - Berlin',122,'Berlin'),
('Automation Engineer - Electrical',84,'Munich'),
('Automation Engineer - Mechanical',84,'Munich'),
('Automotive Computer Vision Researcher',7,'Munich'),
('Autonomous Flight Engineer',84,'Munich'),
('Autoware Foundation Software Architect',12,'Munich'),
('B2B Affiliate Partner Representative',62,'Berlin'),
('B2B Area Sales Manager (Berlin)',67,'Berlin'),
('B2B Content & Social Media Manager',67,'Berlin'),
('B2B Growth Marketing Manager',67,'Berlin'),
('B2B Sales Manager (München)',67,'Munich'),
('Backend Developer',143,'Berlin'),
('Backend Developer',70,'Berlin'),
('Backend Engineer',131,'Berlin'),
('Backend Engineer',99,'Berlin'),
('Backend Engineer',104,'Munich'),
('Backend Engineer',115,'Berlin'),
('Backend Engineer (Process Mining) - Senior - Berlin',122,'Berlin'),
('Backend Software Engineer, Javascript',39,'Berlin'),
('Backend Software Engineer, Reliability',39,'Berlin'),
('Backend Software Engineer, Ruby',39,'Berlin'),
('BI Developer',55,'Berlin'),
('Board Secretary - Hamburg',82,'Hamburg'),
('Brand Marketing Manager',67,'Berlin'),
('Business Analytics Consultant',35,'Munich'),
('Business Analytics Manager',62,'Berlin'),
('Business Consultant',6,'Düsseldorf'),
('Business Developer - Berlin',133,'Berlin'),
('Business Development and Customer Care Working Student - German & Vietnamese Speaker',46,'Berlin'),
('Business Development Director',116,'Berlin'),
('Business Development Intern',71,'Berlin'),
('Business Development Intern - Bank Partnerships France',113,'Berlin'),
('Business Development Intern - Berlin',46,'Berlin'),
('Business Development Intern - Netherlands',113,'Berlin'),
('Business Development Manager',154,'Hamburg'),
('Business Development Manager',68,'Berlin'),
('Business Development Manager',71,'Berlin'),
('Business Development Manager - Enterprise',42,'Berlin'),
('Business Development Manager - HelloFreshGO',67,'Berlin'),
('Business Development Manager - HelloFreshGO',67,'Berlin'),
('Business Development Manager / Strategy and Growth Manager',141,'Berlin'),
('Business Development Manager DACH',43,'Munich'),
('Business Development Manager Germany',4,'Berlin'),
('Business Development Manager, Europe Region',7,'Munich'),
('Business Development Manager, Wheelbase - Germany',98,'Berlin'),
('Business Development Representative',6,'Düsseldorf'),
('Business Development Representative - DACH',134,'Hamburg'),
('Business Development Representative Germany',24,'Berlin'),
('Business Development(Praktikum)',91,'Aachen'),
('Business Intelligence Developer',25,'Berlin'),
('Business Support Coordinator',93,'Frankfurt'),
('Business Support Manager',154,'Hamburg'),
('Business Support Specialist',120,'Munich'),
('C++ Engineer for Database Development',35,'Munich'),
('Calculation Engineer - Aircraft Icing',84,'Munich'),
('Campaign Manager',128,'Berlin'),
('Campus Recruitment Manager',67,'Berlin'),
('Capital Markets Analyst',41,'Berlin'),
('Cash Manager',95,'Berlin'),
('Category Manager',62,'Berlin'),
('Catering Consultant',33,'Berlin'),
('Certifying Staff CAT B2/C within 21G',84,'Munich'),
('Chief of Independent System Monitoring',84,'Munich'),
('City Partnerships Manager',154,'Hamburg'),
('Claim Agent',90,'Berlin'),
('Client Onboarding Manager 🇩🇪 (Berlin)',133,'Berlin'),
('Client Partner',5,'Munich'),
('Client Partner: DACH & Nordics',3,'Berlin'),
('Client Success Manager - Munich',75,'Munich'),
('Collections Specialist',60,'Berlin'),
('Commercial Analyst',82,'Hamburg'),
('Commercial Business Development Representative for DACH',128,'Berlin'),
('Commercial Manager',78,'Berlin'),
('Commercial Manager',78,'Munich'),
('Commercial Manager',82,'Hamburg'),
('Commodity Manager Propulsion',84,'Munich'),
('Communications Manager',35,'Munich'),
('Communications Manager (DACH)',115,'Berlin'),
('Community (Social Media) Manager',84,'Munich'),
('Community Sales Associate',146,'Berlin'),
('Composite Machining Manufacturing Engineer',84,'Munich'),
('Consulting Intern',67,'Berlin'),
('Content Editing Specialist',62,'Berlin'),
('Content Manager',47,'Berlin'),
('Content Marketing Specialist & Redakteur',91,'Aachen'),
('Controller',143,'Berlin'),
('Cook/ Koch',67,'Berlin'),
('Copywriter - Brand Marketing',67,'Berlin'),
('Corporate Development',84,'Munich'),
('Corporate Legal Counsel - German Native Level',65,'Munich'),
('Corporate Sales Intern',70,'Berlin'),
('Country Manager UK',143,'Berlin'),
('Creative Project Manager',67,'Berlin'),
('Creator Partnership Manager',102,'Berlin'),
('CRM and Database Intern (German Speaker)',40,'Munich'),
('CRM Manager',71,'Berlin'),
('CRM Manager',95,'Berlin'),
('CRM Marketing Manager',113,'Berlin'),
('Customer Care Manager',71,'Berlin'),
('Customer Care Manager  - Payroll',104,'Munich'),
('Customer Care Manager / Sales Representative',141,'Berlin'),
('Customer Care Manager 🇩🇪 (Berlin)',133,'Berlin'),
('Customer Engineer',15,'Munich'),
('Customer Marketing Manager',39,'Berlin'),
('Customer Onboarding Manager - Payroll',104,'Munich'),
('Customer Service Agent / Kundenbetreuer',68,'Berlin'),
('Customer Service Agent / Kundenbetreuer an unserem Standort Cottbus',68,'Berlin'),
('Customer Service Agent / Kundenbetreuer- Spanisch / Englisch / Deutsch',68,'Berlin'),
('Customer Service France',99,'Berlin'),
('Customer Service Manager',104,'Munich'),
('Customer Service Specialist',70,'Berlin'),
('Customer Service Specialist  - Payroll',104,'Munich'),
('Customer Service Specialist - French (part-time)',95,'Berlin'),
('Customer Service Specialist - German',95,'Berlin'),
('Customer Service Specialist- French',95,'Berlin'),
('Customer Service Team Lead - French',95,'Berlin'),
('Customer Success Intern',67,'Berlin'),
('Customer Success Lead',83,'Berlin'),
('Customer Success Manager',35,'Munich'),
('Customer Success Manager',104,'Munich'),
('Customer Success Manager 🇩🇪(Berlin)',133,'Berlin'),
('Customer Success Manager- HelloFreshGO',67,'Berlin'),
('Customer Success Senior Manager',103,'Munich'),
('Customer Success Technical Account Manager',22,'Munich'),
('Customer Support Agent',60,'Berlin'),
('Customer Support Agent  - German speaking',60,'Berlin'),
('Customer Support Manager',67,'Berlin'),
('Customer Support Werkstudent/in',83,'Berlin'),
('Data Analyst',62,'Berlin'),
('Data Analyst',39,'Berlin'),
('Data Analyst - Customer Service',62,'Berlin'),
('Data Engineer',78,'Berlin'),
('Data Engineer',82,'Hamburg'),
('Data Engineer',58,'Berlin'),
('Data Engineer',94,'Berlin'),
('Data Engineer',117,'Berlin'),
('Data Engineer - Berlin',122,'Berlin'),
('Data Engineer - Python',78,'Berlin'),
('Data Processing Engineer - Berlin',122,'Berlin'),
('Data Science & Management Consultant',35,'Munich'),
('Data Science Manager, Growth',62,'Berlin'),
('DATA SCIENCE PRODUCT OWNER',81,'Munich'),
('Data Scientist',143,'Berlin'),
('Data Scientist',19,'Berlin'),
('Data Scientist - Senior - Berlin',122,'Berlin'),
('Data Scientist (Entry-level)',35,'Munich'),
('Data Scientist (Marketing Science)',95,'Berlin'),
('DE- Sales Development Representative',73,'Berlin'),
('Debitorenmanager',25,'Berlin'),
('Dein Einstieg im Customer Success',104,'Munich'),
('Delivery Lead / Technical Program Manager - Platform',67,'Berlin'),
('Desktop Application Developer- HelloFreshGO',67,'Berlin'),
('DevOps',41,'Berlin'),
('DevOps Engineer',115,'Berlin'),
('DevOps Engineer',135,'Berlin'),
('DevOps Engineer',58,'Berlin'),
('DevOps Engineer - Berlin',122,'Berlin'),
('DevOps Software Engineer',95,'Berlin'),
('DevOps/Site Reliability Engineer',113,'Berlin'),
('Digital campaign marketing specialist-Berlin',4,'Berlin'),
('Digital Marketing Automation Manager',24,'Berlin'),
('Digital Marketing Manager',29,'Berlin'),
('Digital Marketing Manager (B2B)',67,'Berlin'),
('Director Business Intelligence',104,'Munich'),
('Director Customer Success',58,'Berlin'),
('Director of Advertising',95,'Berlin'),
('Director of Air',95,'Berlin'),
('Director of Enterprise Sales – Munich (DACH Region)',45,'Munich'),
('Director of Mobile / Engineering',95,'Berlin'),
('Director of Product',67,'Berlin'),
('Director of Product - Partner Experience',113,'Berlin'),
('Director of Product Design',113,'Berlin'),
('Director of Solutions DACH (Inventory Presales)',136,'Munich'),
('Director of Technology Platform',104,'Munich'),
('Director SEO',43,'Munich'),
('Dispatcher France',90,'Berlin'),
('Display Marketing Manager',62,'Berlin'),
('Display Marketing Manager',95,'Berlin'),
('Disponent',90,'Berlin'),
('Disponent',141,'Berlin'),
('Disponent / Operative Logistiksteuerung',67,'Berlin'),
('E-Commerce Manager',47,'Berlin'),
('E-Mail Marketing & CRM',91,'Aachen'),
('Ecommerce Associate, French Speaking - Lookfantastic',140,'Berlin'),
('Ecommerce Associate, German Speaking - Lookfantastic',140,'Berlin'),
('Educational Content Manager - In-App Content',104,'Munich'),
('Educational Content Writer',104,'Munich'),
('Einkäufer',141,'Berlin'),
('Electric Systems Engineer VoloDrone',152,'Munich'),
('Embedded Software Developer',70,'Berlin'),
('Embedded Software Developer',70,'Berlin'),
('Embedded Software Engineer for Battery Management System',84,'Munich'),
('EMBEDDED SYSTEMS TECHNICAL LEAD',81,'Munich'),
('EMEA Payroll Specialist- German Speaking (Based in Dublin)',64,'Berlin'),
('Engagement Principal',5,'Munich'),
('Engineering Director',19,'Berlin'),
('Engineering Manager',67,'Berlin'),
('Engineering Manager',17,'Berlin'),
('Engineering Manager',62,'Berlin'),
('Engineering Manager',104,'Munich'),
('Engineering Manager - Java',78,'Berlin'),
('Engineering Manager - JavaScript',78,'Berlin'),
('Engineering Manager – Web API',41,'Berlin'),
('Engineering Manager (Open Source) - Berlin',31,'Berlin'),
('Engineering Manager, Applications',85,'Berlin'),
('Enterprise Account Executive',42,'Berlin'),
('Enterprise Account Executive',148,'Berlin'),
('Enterprise Account Executive - EMEA & APAC',39,'Berlin'),
('Enterprise Account Executive - German Speaking (Hamburg or Munich)',50,'Hamburg'),
('Enterprise Account Executive - Germany',100,'Frankfurt'),
('Enterprise Account Executive (Germany)',149,'Munich'),
('Enterprise Account Executive (Germany)',149,'Berlin'),
('Enterprise Account Executive DACH - New Accounts',97,'Munich'),
('Enterprise Account Executive EMEA',35,'Munich'),
('Enterprise Account Executive EMEA - Strategic Accounts (Remote)',127,'Munich'),
('Enterprise Account Executive EMEA (Berlin)',24,'Berlin'),
('Enterprise Account Manager',93,'Frankfurt'),
('Enterprise Account Manager',15,'Munich'),
('Enterprise Account Manager',93,'Hamburg'),
('Enterprise Solutions Consultant - Remote',126,'Düsseldorf'),
('Enterprise Territory Manager - Munich/Stuttgart',139,'Munich'),
('Entrepreneur in Residence',54,'Berlin'),
('Entrepreneur in Residence',35,'Munich'),
('Entrepreneur in Residence Intern - HelloFreshGO',67,'Berlin'),
('Event Manager',88,'Berlin'),
('Executive Assistant to CEO',84,'Munich'),
('Executive Assistant to the CEO',104,'Munich'),
('Executive Assistant, Product & Engineering',104,'Munich'),
('Expansion & Growth Intern',151,'Berlin'),
('Expansion Management Intern - HelloFreshGO',67,'Berlin'),
('Expansion Project Manager',70,'Berlin'),
('Export Area Manager [#731]',52,'Munich'),
('Field Logistics Partner',151,'Düsseldorf'),
('Field Marketing Manager',110,'Munich'),
('Field Marketing Manager (native German)',53,'Munich'),
('Field Marketing Manager (native German)',53,'Munich'),
('Field Marketing Manager Eastern Europe',110,'Munich'),
('Field Service Engineer',145,'Munich'),
('Finance & Accounting Manager',71,'Berlin'),
('Finance Business Partner - Commercial, Finance & People',84,'Munich'),
('Finance Working Student',39,'Berlin'),
('Finance Working Student',47,'Berlin'),
('Finance Working Student',46,'Berlin'),
('Financial Accountant',82,'Hamburg'),
('Financial Data Analyst',25,'Berlin'),
('Financial Planning and Analysis Lead',82,'Hamburg'),
('Firmenkundenberater',25,'Berlin'),
('FIRMWARE DEVELOPER',81,'Munich'),
('Flight Control Law Engineer',84,'Munich'),
('Flight Physics Engineer - Aircraft Performance',84,'Munich'),
('Flight Test Engineer VoloDrone',152,'Munich'),
('Flight Test Instrumentation Technician',84,'Munich'),
('Food Safety & Quality Assurance - Working Student',67,'Berlin'),
('Food-Stylist',67,'Berlin'),
('Forward Deployed Software Engineer',101,'Munich'),
('Forward Deployed Solution Leader',30,'Paris'),
('Forwarding & Transport Lead',71,'Berlin'),
('Forwarding & Transport Lead',71,'Berlin'),
('FP&A Analyst',82,'Hamburg'),
('Front Desk Agent / Empfangsmitarbeiter – Teilzeit (30h)',67,'Berlin'),
('Front End Engineer',121,'London'),
('Front-End Engineer',115,'Berlin'),
('Front-end Engineer',108,'Berlin'),
('Frontend - Data Visualization Engineer',105,'Berlin'),
('Frontend Developer',59,'Berlin'),
('Frontend Developer',35,'Munich'),
('Frontend Developer',25,'Berlin'),
('Frontend Developer',143,'Berlin'),
('Frontend Engineer',34,'Berlin'),
('Frontend Performance Engineer',105,'Berlin'),
('Full Stack Developer - Node.js / Python / React',126,'Berlin'),
('Full Stack Engineer',108,'Berlin'),
('Full Stack Engineer [#800]',52,'Munich'),
('Full Stack Software Engineer',39,'Berlin'),
('Full-Stack Engineer (Node/React)',154,'Hamburg'),
('Full-Stack Engineer (Paris or/and Berlin)',109,'Paris'),
('Full-Stack Software Engineer',145,'Munich'),
('Full-time Marketing Intern (German speaker)',40,'Munich'),
('Game Designer',77,'Berlin'),
('Game Engineer',77,'Berlin'),
('Game QA Tester',77,'Berlin'),
('General Manager, EMEA',116,'Berlin'),
('German speaker Senior Recruiter (Berlin)',109,'Berlin'),
('GERMANY - Accountant',73,'Berlin'),
('GERMANY - Enterprise Account Executive',73,'Berlin'),
('GERMANY - Head of Finance',73,'Berlin'),
('GERMANY - Head of Integration',73,'Berlin'),
('GERMANY - Service Manager',73,'Berlin'),
('Global Business Development Manager',35,'Munich'),
('Global Marketing Operations/Automation Manager  [#769]',52,'Munich'),
('Global Operations Manager',57,'Hamburg'),
('Global Operations Manager - Berlin',115,'Berlin'),
('Global Operations Manager - Berlin',115,'Berlin'),
('Global Operations Manager (Senior/Lead) - Berlin',115,'Berlin'),
('Global SEO Manager',43,'Munich'),
('Global Vice President of Product - Supply Chain Technologies',67,'Berlin'),
('Go-To-Market Intern - HelloFreshGO',67,'Berlin'),
('Governance PMO Lead',95,'Berlin'),
('Graphic Design Intern – EMEA',63,'Munich'),
('Graphics Engineer',77,'Berlin'),
('Groß- und Außenhandelskaufmann/-frau SHK Baustellenbetreuung',141,'Berlin'),
('Ground Control Systems Engineer VoloDrone',152,'Munich'),
('Group Accountant',67,'Berlin'),
('Group Product Manager - Search & Discovery',62,'Berlin'),
('GROWTH MANAGER',87,'Berlin'),
('Growth Manager',104,'Munich'),
('Growth Manager',71,'Berlin'),
('Hardware and Software Test Engineer',135,'Berlin'),
('Head of B2B Growth - HelloFreshGO',67,'Berlin'),
('Head of B2B Inbound Marketing',67,'Berlin'),
('Head of Business Development - EMEA',86,'Berlin'),
('Head of Business Unit',62,'Berlin'),
('Head of Corporate Quality Assurance',84,'Munich'),
('Head of Corporate Quality Management and Programme Compliance',84,'Munich'),
('Head of Display & Paid Social Marketing',95,'Berlin'),
('HEAD OF FIRMWARE DEVELOPMENT',81,'Munich'),
('Head of Growth - DACH region',115,'Berlin'),
('Head of Growth Marketing',62,'Berlin'),
('Head of Infrastructure Engineering',104,'Munich'),
('Head of Online Community and Learning',147,'Berlin'),
('Head of Partnership CRM',62,'Berlin'),
('Head of Payroll Operations',104,'Munich'),
('Head of Platform',105,'Berlin'),
('Head of Procurement Policies, Processes and Systems',84,'Munich'),
('HEAD OF PRODUCT MANAGEMENT',81,'Munich'),
('Head of Real Estate and Indirect Procurement',95,'Berlin'),
('Head of Sales',55,'Berlin'),
('Head of Sales - DACH',50,'Hamburg'),
('Head of Sales EMEA',24,'Berlin'),
('Head of Site Merchandising',62,'Berlin'),
('Head of Tax / Leiter Steuern',67,'Berlin'),
('Health & Safety Officer',84,'Munich'),
('HR Business Partner',70,'Berlin'),
('HR Business Partner - Berlin',122,'Berlin'),
('HR BUSINESS PARTNER (HRBP), FOCUS PERFORMANCE MANAGEMENT & COMPENSATION',81,'Munich'),
('HR Generalist',62,'Berlin'),
('HR Manager/Generalist',71,'Berlin'),
('HR Operations Specialist – German speaking',64,'Berlin'),
('HR Services Intern',62,'Berlin'),
('HR Team Lead, International',62,'Berlin'),
('HSE Officer',84,'Munich'),
('Hubspot Technical Expert',24,'Berlin'),
('Human Resources Praktikum',91,'Aachen'),
('Implementation Automation Specialist',104,'Munich'),
('Implementation Manager - Payroll',104,'Munich'),
('Implementation Specialist (French and Spanish Speaking)',28,'Berlin'),
('Implementation Specialist (German Speaking)',28,'Berlin'),
('In-Destination Marketing Manager - Berlin',62,'Berlin'),
('In-Destination Marketing Manager - Rome',62,'Berlin'),
('Inbound & Performance Marketing Manager',62,'Berlin'),
('Inbound Marketing Manager - The Netherlands',113,'Berlin'),
('Inbound Sales Representative',104,'Munich'),
('Industrial Designer',70,'Berlin'),
('Information Designer',113,'Berlin'),
('Information Security Manager',67,'Berlin'),
('Inside Sales Manager - HelloFreshGO',67,'Berlin'),
('Installation Specialist',70,'Berlin'),
('Installed Solutions Commercial Lead, DACH & Poland',129,'Munich'),
('Interior Designer (Berlin)',79,'Berlin'),
('Intern Business Development',87,'Berlin'),
('Intern Business Development France',33,'Berlin'),
('Intern Commercial Strategy - HelloFreshGO',67,'Berlin'),
('Intern Content Manager and Copywriter (German) - HelloFreshGO',67,'Berlin'),
('Intern Digital Production',84,'Munich'),
('Intern Finance',33,'Berlin'),
('Intern Manufacturing Engineering Battery Assembly',84,'Munich'),
('Intern Software Engineer (Summer 2020)',34,'Berlin'),
('Internal Brand & Communications Manager [#774]',52,'Munich'),
('Internal consultant internship tech startup',46,'Berlin'),
('Internship Business Analyst',58,'Hamburg'),
('Internship Business Development',58,'Berlin'),
('Internship Data Journalist / Data Analyst (Berlin)',109,'Berlin'),
('Internship Financial Operations',58,'Berlin'),
('Inventory Management Project Manager',62,'Berlin'),
('iOS Engineer',131,'Berlin'),
('IT Admin',71,'Berlin'),
('IT Architect',55,'Berlin'),
('IT Financial Controller',67,'Berlin'),
('IT Incident Manager/ Second Level Support Analyst',113,'Berlin'),
('IT Operations Administrator',58,'Berlin'),
('IT Support Engineer',67,'Berlin'),
('IT System Administrator',62,'Berlin'),
('IT Working Student',131,'Berlin'),
('IT-Produktmanager - Banking Applications',113,'Frankfurt'),
('Java Backend Engineer - Lead - Berlin',122,'Berlin'),
('Java Backend Engineer - Senior  - Berlin',122,'Berlin'),
('Java Full Stack Developer',35,'Munich'),
('JavaScript Frontend Engineer  - Lead  - Berlin',122,'Berlin'),
('JavaScript Frontend Engineer - Senior - Berlin',122,'Berlin'),
('Jr/Mid Backend Developer (API Integration)',47,'Berlin'),
('Junior Account Executive DACH',104,'Munich'),
('Junior Account Executive Germany - Berlin',24,'Berlin'),
('Junior Account Manager Payroll',104,'Munich'),
('Junior Backend Engineer',104,'Munich'),
('Junior Banking Relationship Manager',113,'Berlin'),
('Junior Banking Relationship Manager',113,'Berlin'),
('Junior BI Analyst',113,'Berlin'),
('Junior Billing Specialist',104,'Munich'),
('Junior Business Development Manager',113,'Berlin'),
('Junior Communications Manager',143,'Berlin'),
('Junior Content Copywriter DACH',67,'Berlin'),
('Junior CRM Manager (Campaign Management)',67,'Berlin'),
('Junior Customer Care Manager - Payroll',104,'Munich'),
('Junior Customer Onboarding Manager',104,'Munich'),
('Junior Customer Onboarding Manager - Payroll',104,'Munich'),
('Junior Customer Service Manager',104,'Munich'),
('Junior Customer Service Specialist  - Payroll',104,'Munich'),
('Junior Data QA Analyst',126,'Berlin'),
('Junior Digital Data Analyst',67,'Berlin'),
('Junior Implementation Manager',104,'Munich'),
('Junior Implementation Manager - Payroll',104,'Munich'),
('Junior Organic Mobile Growth Manager',95,'Berlin'),
('Junior Payroll Specialist',104,'Munich'),
('Junior Product Analyst',67,'Berlin'),
('Junior Product Marketing Manager - Sales Enablement',104,'Munich'),
('Junior Project Manager',41,'Berlin'),
('Junior Project Manager',71,'Berlin'),
('Junior Quality Manager DACH',67,'Berlin'),
('JUNIOR RECRUITER & EMPLOYER BRANDING MANAGER',81,'Munich'),
('Key Account Manager',104,'Munich'),
('Key Account Manager',71,'Berlin'),
('Kreditorenbuchhalter (human)',33,'Berlin'),
('Kundendienstmonteur SHK - Region Berlin',141,'Berlin'),
('Kundendienstmonteur SHK - Region Freiburg',141,'Berlin'),
('Kundendienstmonteur SHK - Region Hamburg',141,'Hamburg'),
('Kundendienstmonteur SHK - Region Lörrach',141,'Berlin'),
('Kundendienstmonteur SHK - Region Lübeck',141,'Berlin'),
('Kundendienstmonteur SHK- Region Kiel',141,'Berlin'),
('Kundendienstmonteur SHK- Region Neumünster',141,'Hamburg'),
('Kundendienstmonteur SHK- Region Offenburg',141,'Berlin'),
('Kundendienstmonteur SHK- Region Singen',141,'Berlin'),
('Lead Engineer - Interior',84,'Munich'),
('Lead Product Designer',104,'Munich'),
('Lead QA Engineer',153,'London'),
('LEAD SOFTWARE DEVELOPER',81,'Munich'),
('Lead Software Engineer',121,'London'),
('Lead Software Engineer - Infrastructure',117,'Berlin'),
('Lead Software Engineer (PHP + JS + PGSQL)',71,'Berlin'),
('Lead Supply Partner Connectivity Operations',62,'Berlin'),
('Lean Process Intern',110,'Munich'),
('Legal Counsel',95,'Berlin'),
('Localization Excellence Lead',62,'Berlin'),
('Localization Tooling Specialist',62,'Berlin'),
('Logistics Manager (Fleet & Last Mile)',67,'Berlin'),
('Machine Learning Engineer - Acoustic Modeling',132,'Berlin'),
('Machine Learning Engineer - Computer Vision',115,'Berlin'),
('Machine Learning Engineer · FinCrime',115,'Berlin'),
('Maintenance Specialist; Electrical Safety of Equipment and Infrastructure',84,'Munich'),
('Management Intern Germany',83,'Berlin'),
('Manager - Accounts Receivable',25,'Berlin'),
('Manager Sales',104,'Munich'),
('Manager Sales Engineering EMEA',39,'Berlin'),
('Manager Vollstreckungswesen',60,'Berlin'),
('Manager, Real Estate Transactions',79,'Berlin'),
('MANUFACTURING ENGINEER',81,'Munich'),
('Manufacturing Engineer - Assembly Electronics & Supplier Development',84,'Munich'),
('Manufacturing Engineer - Electrical Machines and Drives',84,'Munich'),
('Manufacturing Engineer - Interiors & Supplier Development',84,'Munich'),
('Manufacturing Engineer - Mechanical Joining Processes',84,'Munich'),
('Manufacturing Engineer - Rotating Components',84,'Munich'),
('Manufacturing Engineer of the Future - Munich',145,'Munich'),
('Manufacturing Engineer- Testing',84,'Munich'),
('Market Development Intern',151,'Berlin'),
('Market Development Intern',151,'Düsseldorf'),
('Market Research Manager',67,'Berlin'),
('Marketing & Communication Specialist',43,'Munich'),
('Marketing BI Digital Analyst',67,'Berlin'),
('Marketing Campaign Manager',39,'Berlin'),
('Marketing Intern',151,'Munich'),
('Marketing Intern',71,'Berlin'),
('Marketing Intern - DACH',36,'Berlin'),
('Marketing Manager - DACH',36,'Munich'),
('Marketing Manager - DACH (Maternity Cover)',36,'Berlin'),
('Marketing Manager Deutschland & Schweiz',68,'Berlin'),
('Marketing Program Manager',102,'Berlin'),
('Marketing Specialist',151,'Hamburg'),
('Marketing Specialist',151,'Düsseldorf'),
('Marketing Specialist',151,'Frankfurt'),
('Mass Properties Engineer',84,'Munich'),
('Materials & Processes (M&P) Engineer',84,'Munich'),
('Mechanical Prototyping & Testing intern',110,'Munich'),
('Meister oder Anlagenmechaniker im Innendienst | Technischer Check',141,'Berlin'),
('Mitarbeiter Customer Service',141,'Berlin'),
('Mitarbeiter im Kundenservice  - auch in Teilzeit möglich',90,'Berlin'),
('Mobile Engineer',34,'Berlin'),
('Modedesign',91,'Aachen'),
('Modeling & Simulation Engineer',84,'Munich'),
('Native Application Developer',19,'Berlin'),
('New Business Developer',71,'Berlin'),
('Office Manager',4,'Berlin'),
('Office Manager',113,'Berlin'),
('Office Manager',67,'Berlin'),
('Office Manager',22,'Munich'),
('Office Manager',141,'Berlin'),
('Office Manager',95,'Berlin'),
('Onboarding Manager',102,'Berlin'),
('Onboarding Specialist',67,'Berlin'),
('Online Campaign Specialist',91,'Aachen'),
('Online Marketing Intern – Influencer Marketing',67,'Berlin'),
('Online Marketing Manager',110,'Munich'),
('Online Merchandising Specialist',91,'Aachen'),
('Operational Excellence Project Associate',70,'Berlin'),
('Operations Engineer/ DevOps',3,'Berlin'),
('Operations Intern',67,'Berlin'),
('Operations Manager',43,'Munich'),
('Operations Manager  Schweiz',68,'Berlin'),
('Operations Manager - Frankfurt, Rhein/Main',86,'Frankfurt'),
('Operations Manager - Munich',86,'Munich'),
('Outbound Marketing Representative',154,'Hamburg'),
('Paid Social Marketing Manager',67,'Berlin'),
('Paris City Manager',62,'Berlin'),
('Part-timer in IT',21,'Dusseldorf'),
('Partner Channel Manager (Berlin)',24,'Berlin'),
('Partner Engineer',117,'Berlin'),
('Partner Marketing Manager',39,'Berlin'),
('Partner Marketing Specialist - Campaigns and Strategy',62,'Berlin'),
('Partnership Manager',4,'Berlin'),
('Partnership Marketing Manager (Contract)',51,'Berlin'),
('Payment & Finance Operations Manager',131,'Berlin'),
('Payroll and Operations Associate',59,'Berlin'),
('Payroll Researcher',104,'Munich'),
('Payroll Specialist',104,'Munich'),
('Payroll Specialist',95,'Berlin'),
('Payroll Specialist / Lohnbuchhalter',67,'Berlin'),
('People Business Partner - Business',154,'Hamburg'),
('People Business Partner - Tech',154,'Hamburg'),
('People Data & Systems Manager',131,'New'),
('People Lead - Berlin',122,'Berlin'),
('People Operations Manager',70,'Berlin'),
('People Operations Manager - International',70,'Berlin'),
('Performance Marketing Intern',43,'Munich'),
('Performance Marketing Manager',104,'Munich'),
('Performance Marketing Manager (Berlin)',24,'Berlin'),
('Performance Marketing Manager SEM',143,'Berlin'),
('Performance Marketing Specialist',43,'Munich'),
('Personalsachbearbeiter',67,'Berlin'),
('PHP Backend Engineer',91,'Aachen'),
('Platform Engineer',35,'Munich'),
('Plus Size Fitting Model',99,'Berlin'),
('PR Manager Germany / Austria',61,'Berlin'),
('Praktikant B2B Sales- HelloFreshGO',67,'Berlin'),
('Praktikant Business Development',33,'Berlin'),
('Praktikant Business Development',68,'Berlin'),
('Praktikant Human Resources',104,'Munich'),
('Praktikant Implementation',104,'Munich'),
('Praktikant Key Account Management',33,'Berlin'),
('Praktikant Process Management',113,'Berlin'),
('Praktikant Product Management / Business Development',113,'Berlin'),
('Praktikant Recruiting',104,'Munich'),
('Praktikant Sales Development - HelloFreshGO',67,'Berlin'),
('Praktikant Sales Management',141,'Berlin'),
('Praktikant Talent Acquisition',104,'Munich'),
('Praktikant Tech Recruiting',104,'Munich'),
('Praktikant(in) Business Development - Bank Partnerships',113,'Berlin'),
('Praktikum im Bereich Operations',90,'Berlin'),
('Praktikum im Kundenservice',90,'Berlin'),
('Presales - Solution Engineer',40,'Munich'),
('Principal Design Engineer',84,'Munich'),
('Principal Engineer',62,'Berlin'),
('Principal Engineer / Lead Architect - Berlin',19,'Berlin'),
('Principal Product Expert',104,'Munich'),
('Principal Software Engineer / Search Platform / Berlin',95,'Berlin'),
('Process Engineering Manager Aircraft Assembly',84,'Munich'),
('Procurement / Prototyping Manager VoloDrone',152,'Munich'),
('Procurement Manager - Compliance & Export Control',84,'Munich'),
('Procurement Manager - Contracts & Templates',84,'Munich'),
('Procurement Manager - ERP & Data Management',84,'Munich'),
('Procurement Specialist – Aircraft Commodity Procurement',84,'Munich'),
('Procurement Specialist – Purchase-to-Pay',84,'Munich'),
('Product Analytics Manager',62,'Berlin'),
('Product Associate - Revolut for Business',115,'Berlin'),
('Product Design Director',95,'Berlin'),
('Product Designer',39,'Berlin'),
('Product Designer - Freelance',67,'Berlin'),
('Product Designer - Market Opportunities',115,'Berlin'),
('Product Designer - UX/UI',68,'Berlin'),
('Product Designer (UX)',3,'Berlin'),
('Product Designer UI/UX',31,'Berlin'),
('Product Engineer (Talent 🇪🇺)',11,'Hamburg'),
('Product Expert',104,'Munich'),
('Product Expert',38,'Frankfurt'),
('Product Knowledge Manager',3,'Berlin'),
('Product Lead  - Berlin',122,'Berlin'),
('Product Lead - Signavio Solutions',122,'Berlin'),
('Product Lead - Technology Partner - Berlin',122,'Berlin'),
('Product Lead for Connect',131,'Berlin'),
('Product Management Intern',67,'Berlin'),
('Product Manager',78,'Berlin'),
('Product Manager',58,'Berlin'),
('Product Manager',55,'Berlin'),
('Product Manager',64,'Berlin'),
('Product Manager - Content Experience',39,'Berlin'),
('Product Manager - Factoring Platform',25,'Berlin'),
('Product Manager - Fulfilment & Production',67,'Berlin'),
('Product Manager - Process Intelligence',122,'Berlin'),
('Product Manager - Risk',25,'Berlin'),
('Product Manager Integrations',104,'Munich'),
('Product Manager Investment Products',113,'Berlin'),
('Product Marketing Lead - Berlin',122,'Berlin'),
('Product Marketing Manager - Core HR & Testversion',104,'Munich'),
('Product Marketing Manager - Global Payroll',104,'Munich'),
('Product Operations Manager (Retail Market Opportunities)',115,'Berlin'),
('Product Owner - Berlin',122,'Berlin'),
('Product Owner - Revolut for Business - CX',115,'Berlin'),
('Product Owner - Revolut for Business - Market Opportunities',115,'Berlin'),
('Product Owner (SCRUM)',141,'Berlin'),
('Product Owner (Smart Fridge)',67,'Berlin'),
('Product Owner Firmenkunden',20,'Düsseldorf'),
('Product Owner Warehouse Control System',67,'Berlin'),
('Production Engineer',131,'Berlin'),
('Produktentwicklung Bekleidung',91,'Aachen'),
('Produktkommunikation Werkstudent DACH',67,'Berlin'),
('Professional Services Consultant',93,'Munich'),
('Program Officer, Global Drug Policy',96,'New'),
('Project Architect (Berlin)',79,'Berlin'),
('Project Lead Marketing Attribution',67,'Berlin'),
('Protocol Engineer',1,'New'),
('Public Relations Manager (DACH)',70,'Berlin'),
('Python Software Engineer',115,'Berlin'),
('QA Automation Engineer',106,'Berlin'),
('QA Engineer - Berlin',122,'Berlin'),
('Quality Assurance Engineer',135,'Berlin'),
('Quality Assurance Engineer (Software and Complex Electronic HW)',84,'Munich'),
('Quality Assurance Engineer (System Level)',84,'Munich'),
('Quality Assurance Manager',71,'Berlin'),
('Quality Inspector Part 21G',84,'Munich'),
('Quality POA Project Manager',84,'Munich'),
('Quality Process Engineer Part 21G',84,'Munich'),
('Real Estate Lead (Germany)',79,'Frankfurt'),
('Real Estate Lead (Germany)',79,'Munich'),
('Receptionist',77,'Berlin'),
('Recoveries Specialist',60,'Berlin'),
('Recruiter',143,'Berlin'),
('Recruiter / Talent Acquisition Manager',3,'Berlin'),
('Recruiting - Sourcer',154,'Hamburg'),
('Recruiting - Sourcer',154,'Hamburg'),
('Recruiting Team Lead',70,'Berlin'),
('Regional Account Executive - Germany',66,'Berlin'),
('Regional Alliance Director DACH (Munich)',156,'Munich'),
('Regional Business Leader, EMEA',117,'Berlin'),
('Regional Marketing Manager (DACH)',70,'Berlin'),
('Regional Operations Intern',151,'Frankfurt'),
('Regional Operations Intern',151,'Hamburg'),
('Regional Operations Intern',151,'Munich'),
('Regional Sales Director - DACH',123,'Munich'),
('REGIONAL SALES DIRECTOR - EASTERN EUROPE (REMOTE)',81,'Munich'),
('Regional Sales Director / Sr Account Executive – DACH',137,'Munich'),
('Regional Sales Manager',92,'Frankfurt'),
('Regional Sales Manager - DACH',119,'Munich'),
('Regional Sales Manager - DACH',37,'Munich'),
('Regional Sales Manager (Germany)',142,'Frankfurt'),
('Regional Sales Manager, Germany',56,'Munich'),
('Regulatory Manager Autonomous Flight',84,'Munich'),
('Repair Partner',151,'Munich'),
('Revolut for Business: Business Developer (DACH)',115,'Berlin'),
('Risk & Collections Analyst',82,'Hamburg'),
('Risk Operations Manager',25,'Berlin'),
('Rome Partnerships Manager',62,'Berlin'),
('Sales & Business Development Manager, Germany - Frankfurt',130,'Frankfurt'),
('Sales & Business Development Manager, Munich - Germany',130,'Munich'),
('Sales & Growth Intern',71,'Berlin'),
('Sales Agent France',90,'Berlin'),
('Sales Consultant France',99,'Berlin'),
('Sales Consultant Netherlands / Belgium (Fulltime)',99,'Berlin'),
('Sales Consultant Sweden',99,'Berlin'),
('Sales Consultant/ BizDev intern Berlin',46,'Berlin'),
('Sales Development Representative',57,'Hamburg'),
('Sales Development Representative',104,'Munich'),
('Sales Development Representative - English speaking',39,'Berlin'),
('Sales Development Representative - German speaking',39,'Berlin'),
('Sales Development Representative - German speaking - Munich',53,'Munich'),
('Sales Development Representative Benelux',104,'Munich'),
('Sales Development Representative Nordics',104,'Munich'),
('Sales Development Representative, EU',106,'Berlin'),
('Sales Director',10,'Frankfurt'),
('Sales Enablement Manager',104,'Munich'),
('Sales Engineer',92,'Munich'),
('Sales Engineer',32,'Munich'),
('Sales Engineer - Cyber Security - Frankfurt',44,'Frankfurt'),
('Sales Engineer - Cyber Security - Munich',44,'Munich'),
('Sales Engineer / Solutions Engineer, Germany',155,'Munich'),
('Sales Executive - DACH',144,'Berlin'),
('Sales Executive - EMEA',72,'Berlin'),
('Sales Manager Mid Market EE & Russia',3,'Berlin'),
('Sales Manager Working Student',70,'Berlin'),
('Sales Operations Manager',104,'Munich'),
('Sales Solutions Consultant',138,'Munich'),
('Salesforce Administrator',60,'Berlin'),
('Salesforce Administrator',114,'Berlin'),
('Salesforce Product Owner',104,'Munich'),
('Salesforce QA Engineer',25,'Berlin'),
('Salesforce Specialist - Berlin',122,'Berlin'),
('Satellite Data Processing Engineer',106,'Berlin'),
('SCR Efficiency & QA Analyst',60,'Berlin'),
('Scrum Master',118,'Berlin'),
('SDE - Cloud Platform',64,'Berlin'),
('SEM Manager',95,'Berlin'),
('Senior (Lead) 3D Animator',77,'Berlin'),
('Senior Account Executive',13,'Berlin'),
('Senior Account Executive DACH',104,'Munich'),
('Senior Account Executive Germany - Berlin',24,'Berlin'),
('Senior Account Manager',25,'Berlin'),
('Senior Accountant / Buchhalter',33,'Berlin'),
('Senior Affiliate Marketing Manager',113,'Berlin'),
('Senior Agile Coach',67,'Berlin'),
('Senior Android Developer',115,'Berlin'),
('Senior Android Engineer',62,'Berlin'),
('Senior Application Consultant',88,'Berlin'),
('Senior Application Support Engineer',62,'Berlin'),
('SENIOR BACKEND DEVELOPER',81,'Munich'),
('Senior Backend Engineer',105,'Berlin'),
('Senior Backend Engineer',115,'Berlin'),
('Senior Backend Engineer',104,'Munich'),
('Senior Backend Engineer',31,'Berlin'),
('Senior Backend Engineer - Real-time Data',67,'Berlin'),
('Senior Backend Engineer (Golang/Python/PHP)',67,'Berlin'),
('Senior Backend Engineer (Java / Golang / Node.js) - Monetisation Team',95,'Berlin'),
('Senior Backend Enginer',95,'Berlin'),
('Senior Backend Ruby Developer',47,'Berlin'),
('Senior Backend Software Engineer [MG, Organic]',95,'Berlin'),
('Senior Backend Software Engineer w/Data [MG Performance]',95,'Berlin'),
('Senior Brand / Market Researcher',62,'Berlin'),
('Senior Business Analytics Consultant',35,'Munich'),
('Senior Business Development Manager / Entrepreneur in Residence',67,'Berlin'),
('Senior Business Intelligence Consultant',9,'Munich'),
('Senior Business Intelligence Engineer - Financial Systems Team',64,'Berlin'),
('Senior CAD Designer - Electrical Harness Design',84,'Munich'),
('Senior CAD Designer - Surface design',84,'Munich'),
('Senior Cell Engineer – Technology',84,'Munich'),
('Senior Consultant - Germany',14,'Frankfurt'),
('Senior Copywriter',95,'Berlin'),
('Senior Creative Project Manager',67,'Berlin'),
('Senior CRM Manager',131,'New'),
('Senior CRM Manager',43,'Munich'),
('Senior Cryptography Engineer',34,'Berlin'),
('Senior Customer Marketing Manager',104,'Munich'),
('Senior Customer Service Agent',68,'Berlin'),
('Senior Customer Success Manager',124,'Munich'),
('Senior Customer Success Manager / Growth Manager',141,'Berlin'),
('Senior DACH Marketing Manager',139,'Munich'),
('Senior DACH Marketing Manager',139,'Munich'),
('Senior Data Engineer',67,'Berlin'),
('Senior Data Engineer, Data Platform',131,'Berlin'),
('Senior Data Scientist',67,'Berlin'),
('Senior Data Scientist  | Hamburg',82,'Hamburg'),
('Senior Data Scientist - Data Product',62,'Berlin'),
('Senior Data Scientist Recommendations',131,'Berlin'),
('Senior Database Reliability Engineer',124,'Dublin'),
('Senior Destination Manager Germany',62,'Berlin'),
('SENIOR DEVOPS ENGINEER',81,'Munich'),
('Senior DevOps Engineer',99,'Berlin'),
('Senior DevOps Engineer',95,'Berlin'),
('Senior Digital Marketing Manager',43,'Munich'),
('Senior Digital Marketing Manager DE',143,'Berlin'),
('Senior Digital Performance Marketing Manager',60,'Berlin'),
('Senior Director, Telecom and Media Sales',30,'Munich'),
('Senior Employment Counsel - EMEA',86,'Berlin'),
('Senior Engineer Distributed Systems',99,'Berlin'),
('Senior Enterprise Field Sales Representative',111,'Munich'),
('Senior Enterprise Sales Manager',25,'Berlin'),
('Senior Event Marketing Manager',104,'Munich'),
('Senior Export Control Officer',84,'Munich'),
('Senior Field Application Engineer',12,'Munich'),
('Senior Finance BI Analyst',67,'Berlin'),
('Senior Financial Accountant',82,'Hamburg'),
('Senior Flight Control Law Engineer',84,'Munich'),
('Senior Front-End Engineer',99,'Berlin'),
('Senior Frontend Developer',25,'Berlin'),
('Senior Frontend Developer - JavaScript / React (Marketing Growth)',95,'Berlin'),
('Senior Frontend Engineer',105,'Berlin'),
('Senior Frontend Engineer',31,'Berlin'),
('Senior Frontend Engineer',58,'Berlin'),
('Senior Frontend Engineer — Security',105,'Berlin'),
('Senior Frontend Engineer (React Native + Web) - UI Platform',95,'Berlin'),
('Senior Frontend Engineer / Monetisation Team / Javascript (React/Redux stack, ES6)',95,'Berlin'),
('Senior Full-Stack Engineer',62,'Berlin'),
('Senior Full-Stack Engineer  (TypeScript + Node.js / React.js), User Profile Team',95,'Berlin'),
('Senior Fullstack Software Engineer (Node.js & Typescript) / Checkout Team / Berlin',95,'Berlin'),
('Senior Fullstack/Ruby Developer',68,'Berlin'),
('Senior Global Mobility Specialist',84,'Munich'),
('Senior HIL Engineer - System Integrator',84,'Munich'),
('Senior HR Operations Specialist',84,'Munich'),
('Senior Inbound Marketing Manager: DE',143,'Berlin'),
('Senior Industrial Engineer - New Factories',84,'Munich'),
('Senior iOS Engineer',62,'Berlin'),
('Senior Java Developer',35,'Munich'),
('Senior Java Developer',95,'Berlin'),
('Senior Java Engineer',118,'Berlin'),
('Senior Java Software Engineer - Backend / Coverage Foundation Team',95,'Berlin'),
('Senior Legal Counsel',67,'Berlin'),
('Senior Legal Counsel – Datenschutzrecht',67,'Berlin'),
('Senior Legal Counsel / Rechtsanwalt',84,'Munich'),
('Senior Level Artist',77,'Berlin'),
('Senior Lifecycle Marketing Manager',105,'Berlin'),
('Senior Manager Capital Markets & Institutional Investors',20,'Düsseldorf'),
('Senior Manager, Regional Professional Services Delivery, DACH',48,'Frankfurt'),
('Senior Marketing BI Developer',67,'Berlin'),
('Senior Materials & Processes (M&P) Engineer',84,'Munich'),
('Senior Mechanical Engineer - Interior',84,'Munich'),
('Senior Mobile Developer (React/React Native)',113,'Berlin'),
('Senior Paid Social Marketing Manager',67,'Berlin'),
('Senior People Partner',95,'Berlin'),
('Senior Performance Marketing Lead',59,'Berlin'),
('Senior Performance Marketing Manager',68,'Berlin'),
('Senior Performance Marketing Manager SEM',143,'Berlin'),
('Senior Pricing Analyst',20,'Düsseldorf'),
('Senior Product Analyst',114,'Berlin'),
('Senior Product Designer',126,'Berlin'),
('Senior Product Designer',108,'Berlin'),
('Senior Product Designer - On Trip',62,'Berlin'),
('Senior Product Designer UI/UX',31,'Berlin'),
('Senior Product Designer, Search & Recommendations',131,'Berlin'),
('SENIOR PRODUCT MANAGER',81,'Munich'),
('Senior Product Manager',59,'Berlin'),
('Senior Product Manager',95,'Berlin'),
('Senior Product Manager - Marketplace Tooling',62,'Berlin'),
('Senior Product Manager - Monetisation',95,'Berlin'),
('Senior Product Manager - Recommendations & Relevance',62,'Berlin'),
('Senior Product Manager - Retention',95,'Berlin'),
('Senior Product Manager (Business Software)',70,'Berlin'),
('Senior Product Manager SaaS',104,'Munich'),
('Senior Product Manager, Discovery',131,'Berlin'),
('Senior Product Owner',154,'Hamburg'),
('Senior Project Manager',9,'Berlin'),
('Senior Project Manager - Landing infrastructure',84,'Munich'),
('Senior QA Engineer',67,'Berlin'),
('Senior React Native Engineer',105,'Berlin'),
('Senior Recruiter',104,'Munich'),
('Senior Recruiter - German speaking',64,'Berlin'),
('Senior Recruiter - German speaking',64,'Berlin'),
('Senior Recruiter - Sales',143,'Berlin'),
('Senior Recruiter (focus Tech)',70,'Berlin'),
('Senior Requirements Management Engineer',84,'Munich'),
('Senior Research Scientist',85,'Berlin'),
('Senior Search Relevance Engineer',131,'Berlin'),
('Senior SEO Consultant',62,'Berlin'),
('Senior SEO Manager',43,'Munich'),
('Senior Site Reliability Engineer (DevOps)- BER  [#715]',52,'Berlin'),
('Senior Site Reliability Engineer (DevOps)- MUC [#715]',52,'Munich'),
('Senior Site Reliability Engineer (SRE)',67,'Berlin'),
('Senior Software Architect',58,'Berlin'),
('Senior Software Engineer',34,'Berlin'),
('Senior Software Engineer',25,'Berlin'),
('Senior Software Engineer',135,'Berlin'),
('Senior Software Engineer',64,'Berlin'),
('Senior Software Engineer - Backend',62,'Berlin'),
('Senior Software Engineer - Backend/ Coverage/ Connection Excellence Team',95,'Berlin'),
('Senior Software Engineer - Backend/ Routing/ Multimodal Journeys Team',95,'Berlin'),
('Senior Software Engineer - Coverage',95,'Berlin'),
('Senior Software Engineer - Ferries',95,'Berlin'),
('Senior Software Engineer - Search',131,'Berlin'),
('Senior Software Engineer - Search Platform',95,'Berlin'),
('Senior Software Engineer (React Native, iOS, Android, Web) - UI Platform',95,'Berlin'),
('Senior Software Engineer / Full-Stack Web Developer (PHP + JS + PGSQL)',71,'Berlin'),
('Senior Software Engineer / PHP Backend Specalist (PHP + PGSQL)',71,'Berlin'),
('Senior Software Engineer, Frontend',85,'Berlin'),
('Senior Software Engineer, Research',85,'Berlin'),
('Senior Software Engineer, Site Reliability',85,'Berlin'),
('Senior Solution Architect – ERP & Supply Chain',84,'Munich'),
('Senior Solution Engineer',135,'Berlin'),
('Senior Solutions Engineer (pre-sales) DACH & BeNeLux - Remote',127,'Berlin'),
('Senior Solutions Engineer (pre-sales) DACH & BeNeLux - Remote',127,'Munich'),
('Senior Strategic Accounts Manager Transportation',62,'Berlin'),
('Senior Systems Engineer for power electronics and electric drives  [#725]',52,'Munich'),
('Senior Tax Manager',62,'Berlin'),
('Senior Tech & Product Recruiter',99,'Berlin'),
('Senior Tech Manager',91,'Aachen'),
('Senior Tech Recruiter',154,'Hamburg'),
('Senior Tech Recruiter (Engineering)',62,'Berlin'),
('Senior Tech Recruiter / Recruitment Manager',95,'Berlin'),
('SENIOR TECHNICAL EXPERT RAILWAY',81,'Munich'),
('Senior Technical Project Buyer',70,'Berlin'),
('Senior Technical Training Specialist - EMEA, remote',39,'Berlin'),
('Senior Test Engineer - Battery',84,'Munich'),
('Senior Test Engineer - Structures',84,'Munich'),
('Senior Tool Engineer (Polarion ALM)',84,'Munich'),
('Senior UI Designer',143,'Berlin'),
('Senior UI/UX Designer',35,'Munich'),
('Senior UX Designer',143,'Berlin'),
('Senior UX Researcher',113,'Berlin'),
('Senior UX Researcher',62,'Berlin'),
('Senior UX Researcher',104,'Munich'),
('Senior UX Writer (English)',62,'Berlin'),
('Senior UX/UI Designer',77,'Berlin'),
('Senior Verification Engineer',84,'Munich'),
('SEO Marketing Manager (Berlin)',24,'Berlin'),
('Service Fahrer in Vollzeit (Berlin)',67,'Berlin'),
('SITE RELIABILITY ENGINEER',81,'Munich'),
('Site Reliability Engineer',78,'Berlin'),
('Site Reliability Engineer Freelance',58,'Berlin'),
('Social Media & Communication Marketing Specialist',43,'Munich'),
('Social Media & Communications',91,'Aachen'),
('Social Media Manager DACH',67,'Berlin'),
('Software Development Engineer',64,'Berlin'),
('Software Development Engineer II',64,'Berlin'),
('Software Engineer',94,'Berlin'),
('Software Engineer',8,'Berlin'),
('Software Engineer',34,'Berlin'),
('Software Engineer',105,'Berlin'),
('Software Engineer',19,'Berlin'),
('Software Engineer - Backend',117,'Berlin'),
('Software Engineer - Coverage Team',95,'Berlin'),
('Software Engineer - Full-stack',83,'Berlin'),
('Software Engineer - Java',78,'Berlin'),
('Software Engineer - JavaScript',78,'Berlin'),
('Software Engineer / Web Developer (PHP + JS)',71,'Berlin'),
('Software Engineer Cloud Banking Services',113,'Frankfurt'),
('Software Engineer Cloud Banking Services',113,'Frankfurt'),
('Software Engineer, Infrastructure',153,'London'),
('Software Platforms Engineer',84,'Munich'),
('Solution Architect',110,'Munich'),
('Solution Architect, Professional Services',37,'Frankfurt'),
('Solution Consultant (Pre Sales)',93,'Hamburg'),
('SOLUTION ENGINEER',81,'Munich'),
('Solutions Engineer',16,'Berlin'),
('Solutions Engineer - Berlin',122,'Berlin'),
('Solutions Engineer - Munich',18,'Munich'),
('Sourcer',54,'Berlin'),
('Spanish Language Specialist',62,'Berlin'),
('Sr. Application Engineer',12,'Munich'),
('Sr. Manager Strategischer Einkauf',67,'Berlin'),
('Sr. Product Designer  - Berlin',122,'Berlin'),
('Sr. Product Manager, Technical (Platforms - Data)',94,'Berlin'),
('Sr. Solutions Engineer',124,'Munich'),
('SRE/Infrastructure Engineer',34,'Berlin'),
('Stage Sales France',90,'Berlin'),
('Startup BizDev Intern  - Vietnamese & German Speaker',46,'Berlin'),
('Strategic Accounts Manager',116,'Berlin'),
('Strategic BizDev Manager',47,'Berlin'),
('Strategic Enterprise Account Executive',18,'Munich'),
('Strategic Management Consultant',35,'Munich'),
('Strategic Partner Manager, EMEA',86,'Berlin'),
('Strategic Projects Intern',67,'Berlin'),
('Strategic Projects Manager',67,'Berlin'),
('Strategic Projects SCM Intern',67,'Berlin'),
('Strategic Projects SCM Manager',67,'Berlin'),
('Studentischer Mitarbeiter Customer Experience',20,'Düsseldorf'),
('Styling / Fashion',91,'Aachen'),
('Supply Chain Manager',67,'Berlin'),
('Supply Chain Operations Manager',84,'Munich'),
('Supply Chain Quality Engineer',84,'Munich'),
('Supply Manager',143,'Berlin'),
('Support Engineer',85,'Berlin'),
('System Administrator - Office IT',113,'Berlin'),
('System Administrator (part time) - 6 months fixed term contract',84,'Munich'),
('System Engineer - Electrical Powertrain',84,'Munich'),
('System Engineer- Avionics / Electrical / Electronics',84,'Munich'),
('System Engineer- Battery',84,'Munich'),
('System Engineer, Service Provider- DACH',123,'Munich'),
('Systems Integration Analyst',104,'Munich'),
('Talent Acquisition Manager',41,'Berlin'),
('Talent Acquisition Manager - Business',104,'Munich'),
('Talent Acquisition Manager - Tech',104,'Munich'),
('Talent Acquisition Manager - Tech',67,'Berlin'),
('Talent Coordinator',104,'Munich'),
('Talent Development Specialist',62,'Berlin'),
('Talent Resourcer / Talent Acquisition Specialist (German Speaker)',23,'Frankfurt'),
('Talent Sourcer',104,'Munich'),
('Talents wanted',104,'Munich'),
('Tax Advisor',104,'Munich'),
('Tax Consultant',104,'Munich'),
('Tax manager',95,'Berlin'),
('Tax Manager / Steuerreferent',67,'Berlin'),
('Team Lead - Digital Marketing & Online Publishers Europe',62,'Berlin'),
('Team Lead - SEO & Online Publishers Americas & Australia',62,'Berlin'),
('Team Lead Account Executive',104,'Munich'),
('Team Lead Back End',113,'Berlin'),
('Team Lead CI/CD',113,'Berlin'),
('Team Lead Claims',89,'Berlin'),
('Team Lead for Technicians & Electricians',84,'Munich'),
('Team Lead Marketing Analytics',67,'Berlin'),
('Team Lead Partner Bank Operations',113,'Berlin'),
('Team Lead Procurement Operations DACH',67,'Berlin'),
('Team Lead Site Reliability Engineering [#715]',52,'Munich'),
('Team Lead Software Engineering',58,'Berlin'),
('Team Leader - Software Platforms',84,'Munich'),
('Team Leader – Production Academy',84,'Munich'),
('Team Leader Manufacturing Engineering Composite Processes',84,'Munich'),
('Team Leader Quality Inspection Part 21G',84,'Munich'),
('Team Leader Quality Process Management Part 21G',84,'Munich'),
('Teamlead After Sales',104,'Munich'),
('Teamlead Customer Service',104,'Munich'),
('Teamlead Growth',104,'Munich'),
('Teamlead Payroll Operations',104,'Munich'),
('Teamlead Performance Marketing',141,'Berlin'),
('Teamlead Sales B2C Netherlands',143,'Berlin'),
('Teamlead Sales Development',104,'Munich'),
('Tech Consultant',113,'Berlin'),
('Tech Consultant',113,'Berlin'),
('Technical Account Manager',3,'Berlin'),
('Technical Integration Engineer (Munich)',26,'Munich'),
('Technical Product Owner (SCRUM)',141,'Berlin'),
('Technical Program Manager',94,'Berlin'),
('Technical Program Manager',104,'Munich'),
('Technical Program Manager (Customer, Merchant and Support, Programs)',64,'Berlin'),
('Technical Project Manager',107,'Berlin'),
('Technical Recruiter',34,'Berlin'),
('Technical Support Engineer - Java',31,'Berlin'),
('Technical Writer',94,'Berlin'),
('Telemarketing Agent Netherlands/Belgium in Berlin',99,'Berlin'),
('Tender Manager',71,'Berlin'),
('Territory Director - Central Europe & Russia',13,'Berlin'),
('Test Engineer - Manufacturing Engineer Battery Module',84,'Munich'),
('Trainee Customer Success & Operations',90,'Berlin'),
('Trainee Sales',104,'Munich'),
('Training Manager',3,'Berlin'),
('Training Specialist',104,'Munich'),
('Transaction Manager',41,'Berlin'),
('Transport Manager',71,'Berlin'),
('Travel Sales Manager Netherlands',143,'Berlin'),
('Travel Sales Manager UK',143,'Berlin'),
('Treasury Analyst',59,'Berlin'),
('UI Developer',35,'Munich'),
('UX Writer - Freelance',67,'Berlin'),
('UX-UI Intern',87,'Berlin'),
('UX/UI Designer  [#752]',52,'Munich'),
('Vehicle Operations Specialist',151,'Frankfurt'),
('Vehicle Operations Specialist',151,'Düsseldorf'),
('Vehicle Operations Specialist',151,'Aachen'),
('Vehicle Operations Specialist',151,'Munich'),
('Vehicle Operations Specialist',151,'Karlsruhe'),
('Vehicle Operations Specialist',151,'Hamburg'),
('Verification Engineer',84,'Munich'),
('Vertrieb Außendienst Berlin (Restaurantbranche)',46,'Berlin'),
('Vertrieb Außendienst Hamburg (Restaurantbranche)',46,'Hamburg'),
('Vertrieb Außendienst Köln (Restaurantbranche)',46,'Köln'),
('Vertriebsassistenz',67,'Berlin'),
('Vertriebsassistenz - HelloFreshGO',67,'Berlin'),
('Vice President of Sales - Oil & Gas - Berlin',30,'Berlin'),
('Video Content Producer',122,'Berlin'),
('Visiting Form Analyst (Berlin)',54,'Berlin'),
('Visual Design(Praktikum)',91,'Aachen'),
('VP Procurement',84,'Munich'),
('Warehouse Manager',151,'Frankfurt'),
('Werkstudent  Product Portfolio',141,'Berlin'),
('Werk­stu­dent - Daten­an­no­ta­tion für Machine Lear­ning',25,'Berlin'),
('Werkstudent Catering Consulting',33,'Berlin'),
('Werkstudent Customer Service',141,'Berlin'),
('Werkstudent Finance - Billing',104,'Munich'),
('Werkstudent im Kundenservice',90,'Berlin'),
('Werkstudent Kommunikation & Operations',113,'Berlin'),
('Werkstudent Operations',68,'Berlin'),
('Werkstudent Operations & Relations',113,'Berlin'),
('Werkstudent PR & Social Media',104,'Munich'),
('Werkstudent Recruiting',104,'Munich'),
('Werkstudent/-in Inbound Marketing',113,'Berlin'),
('Working Student - Sales Controlling - Berlin',122,'Berlin'),
('Working Student / Intern in Communications',41,'Berlin'),
('Working Student / Internship SEO tools/technical customer support',76,'Berlin'),
('Working Student Finance',71,'Berlin'),
('Working Student Financial Operations',58,'Berlin'),
('Working Student in Business Development',41,'Berlin'),
('Working Student in the Compliance Department',41,'Berlin'),
('Working Student Marketing',90,'Berlin'),
('Working Student Payroll Operations',104,'Munich'),
('Working Student Rate Management',58,'Berlin'),
('Working Student, Global Customer Success',106,'Berlin'),
('Workplace Experience Manager (Office Manager) - Berlin',115,'Berlin');
