insert into investors(name)
values 
('A/O PropTech'),
('Accel'),
('Andreessen Horowitz'),
('Angel Funded'),
('Anita Borg Institute for Women in Technology'),
('Atomico'),
('Bain Capital Ventures'),
('Balderton Capital'),
('Benchmark'),
('Berkeley SkyDeck'),
('Bessemer Venture Partners'),
('Blumberg Capital'),
('Canvas Ventures'),
('Clear Ventures'),
('Cota Capital'),
('Cowboy Ventures'),
('DCM Ventures'),
('Fifth Wall'),
('First Round Capital'),
('Founders Fund'),
('Greenspring Associates'),
('GSV AcceleraTE'),
('GV'),
('Highland Europe'),
('Index Ventures'),
('Intel Capital'),
('IVP'),
('Menlo Ventures'),
('New Enterprise Associates'),
('Northzone'),
('Norwest Venture Partners'),
('Omidyar Network'),
('Playground Global'),
('Rocket Internet'),
('Sequoia Capital'),
('Shasta Ventures'),
('Summit Partners'),
('Swisscom'),
('Tenaya Capital'),
('Venture Capital Fund'),
('Venture Funded'),
('Webb Investment Network'),
('Wildcat Venture Partners');
